### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by matthieugras** [avafinger/bananapi-zero-ubuntu-base-minimal#10]
I can only see a bunch of precompiled packages.

**Comment by avafinger** [comment]
* Kernel source code is here: https://www.kernel.org/  (4.17, 4.18 you need to apply the patches from megous, icenowy (linux-sunxi). You can find the patch set on Armbian
* U-Boot 2017.09 with the CD pin patch from the maker
* mali driver is here: https://github.com/mripard/sunxi-mali

**Comment by matthieugras** [comment]
Thank you!
