### ISSUE TITLE
iotop

### ISSUE THREAD

**Issue by adovidiu** [avafinger/bananapi-zero-ubuntu-base-minimal#12]
Hi. Would you please add support for iotop? It requires I/O accounting support (CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING) enabled in kernel. Thank you.

**Comment by avafinger** [comment]
I enabled those on the latest kernel 4.19.4, please try this: https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/commit/0aba39074f67292b082a64dc10da9212adfa593e

**Comment by avafinger** [comment]
Kernel 4.19.5 LTS with mali working: https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/commit/7a1c530f8f82bd65217dcdc1e85d4593efc7bc0d
