### ISSUE TITLE
Default username/password?

### ISSUE THREAD

**Issue by RuhanSA079** [avafinger/bananapi-zero-ubuntu-base-minimal#13]
Hi all, 

I flashed my 16gb sdcard with provided built v2 image, but it seems I can't login to the system via serial term.

I tried root/toor, pi/raspberry pi/bananapi...

**Comment by RuhanSA079** [comment]
Never mind.

**Comment by dargow** [comment]
I also can't found it

**Comment by RuhanSA079** [comment]
Find it here:
https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal#connecting-to-ap-via-wifi
