### ISSUE TITLE
Bluetooth 4.20-rc3 not working

### ISSUE THREAD

**Issue by thiagobucca** [avafinger/bananapi-zero-ubuntu-base-minimal#14]
Hello, i'm trying the instructions on the main page to get Bluetooth working, however i'm not getting it to work, i'm stuck in the following line:

`brcm_patchram_plus -d --patchram /lib/firmware/ap6212/bcm43438a1.hcd --enable_hci --bd_addr 11:22:33:44:55:66 --no2bytes --tosleep 5000 /dev/ttyS1
`
result is:

`:44:55:66 --no2bytes --tosleep 5000 /dev/ttyS1
option patchram with arg /lib/firmware/ap6212/bcm43438a1.hcd
file /lib/firmware/ap6212/bcm43438a1.hcd could not be opened, error 2`

it seems that don't have this file **bcm43438a1.hcd**

checking in the directory i only have **bcm43438a0.hcd**

i'm on kernel 4.20-rc3

**Comment by avafinger** [comment]
I think V2 rootfs should have it, in any case, please download and copy the firmware.

Refer to: https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/v10.1

**Comment by thiagobucca** [comment]
Thanks, it worked, however when i reboot its not working again, is there a way to made this persistant across reboots?

**Comment by avafinger** [comment]
Yes, there is. You should install and run a service at boot to patch the firmware. You can resort to the bt service from a legacy image. I will do it soon but can't promise a time frame..

**Comment by thiagobucca** [comment]
Sure, thank you. I'll be happy to test when its ready.

**Comment by avafinger** [comment]
@thiagobucca 
You can use the same trick i used for the NanoPi M4 to enable Bluetooth at every boot.
You don't need to install the service described there just the trick in rc.local: 

Refer to:
https://github.com/avafinger/nanopi-m4-ubuntu-base-minimal#bluetooth

* create the **/etc/rc.local**
* add the complete **brcm_patchram_plus** command

PS. you may need the complete path to brcm_patchram_plus

**Comment by thiagobucca** [comment]
just tried and unfortunately that didn't worked for me. I tried with both the rc.local script from your nanopi-m4 repo and just adding the instructions from this repo to my rc.local

when i list the bluetooth devices with hcitool devi i get blank line:

`Devices:`
when i try to attach it again with hciattach /dev/ttyS1 any i get:

`Can't set line discipline: Device or resource busy
Can't initialize device: Device or resource busy`

**Comment by avafinger** [comment]
Please, try this before the call to brcm_patchram_plus:

**rfkill unblock bluetooth**

**Comment by thiagobucca** [comment]
No go yet, same output.

Here's my rc.local file:

`rfkill unblock bluetooth`
`brcm_patchram_plus -d --patchram /lib/firmware/ap6212/bcm43438a1.hcd --enable_hci --bd_addr 11:22:33:44:55:66 --no2bytes --tosleep 5000 /dev/ttyS1`
`exit 0`

My kernel version:

`Linux bananapizero 4.20.0-rc3-m2z-otg-gadget`

**Comment by avafinger** [comment]
the rc.local is correct. I will try another approach if it works i post it here.

**Comment by avafinger** [comment]
@thiagobucca  
Here is the proper way to enable the BT

the content of /etc/rc.local:

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

#enable BT
brcm_patchram_plus -d --patchram /lib/firmware/ap6212/bcm43438a1.hcd --enable_hci --bd_addr 11:22:33:44:55:66 --no2bytes --tosleep 5000 /dev/ttyS1  > /tmp/bt.log 2>&1 &

exit 0
#!/bin/bash

```
You can check the content of /tmp/bt.log for any errors.

**Comment by avafinger** [comment]
A more elegant way of doing:
https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal#enbale-bluetooth-on-next-boot-permanently

**Comment by thiagobucca** [comment]
thanks, it worked!

**Comment by avafinger** [comment]
https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/firmware-v1.0
