### ISSUE TITLE
VETH kernel module

### ISSUE THREAD

**Issue by AODtorusan** [avafinger/bananapi-zero-ubuntu-base-minimal#22]
I'm trying to run an lxc container on the Banana Pi BPI-P2 ZERO, with the latest 4.20.0-rc3 image, but its complaining about creating the veth devices. It seems that the veth kernel module is not available.

Would it be possible the create a new kernel with the veth ko available? Or post the kernel sources  &config, so I can compile my own module?

**Comment by avafinger** [comment]
#15
