### ISSUE TITLE
Could we use lima drivers on these kernel??

### ISSUE THREAD

**Issue by ghost** [avafinger/bananapi-zero-ubuntu-base-minimal#23]
Hi!! Thanks to the effort.

**Comment by avafinger** [comment]
I think it is possible. I don't have experience with lima.

You need mainline kernel 5.2.y and set CONFIG_DRM_LIMA=y and then build mesa.
Basic instructions are here: https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal#build-your-own-kernel

**Comment by ghost** [comment]
thanks!
