### ISSUE TITLE
boot_kernel_4.17.y.tar.gz only contains kernel zImage_4.17.3-5

### ISSUE THREAD

**Issue by Anoyomouse** [avafinger/bananapi-zero-ubuntu-base-minimal#3]
Hi

I tried flashing an SD card for my banana pi, and the boot kernel only contains kernel 4.17.3, and not 4.17.4, which means it can't load any modules and the system boots, but with no modules (or WiFi)

Any change you could update your tar.gz to contain the correct kernel?

Thanks

**Comment by avafinger** [comment]
Sorry about that! I will fix that. Please, check back in a few hours.

**Comment by avafinger** [comment]
Can you please try again and see if it's been fixed?

**Comment by Anoyomouse** [comment]
Woo

It's working!

Two small things:
1) your flash script is called flash_sdcard_**mz2**_v2.sh, not "m2z"
2) your flash script refers to: bootloader_m2z_v2.bin and not bootloader_m2z.bin (i just made a symlink to the new file and it worked)

Thanks

**Comment by avafinger** [comment]
Thanks for the info, i am updating to kernel 4.17.8 in a few hrs...

**Comment by Anoyomouse** [comment]
is it possible to bundle the update as an update (boot + modules directory) for easy upgrading of existing flashed images?

**Comment by avafinger** [comment]
I just pushed linux-image-4.17.8-m2z_1.0-1.deb.
To update the kernel, issue in shell:

`sudo dpkg -i linux-image-4.17.8-m2z_1.0-1.deb `
and then:
`sync && sudo reboot`
it will update to **kernel 4.17.8** with kernel-headers.

I have changed for some experiments the freq. kernel checks DVFS, it is more responsive but has a 5ºC increase on Temp. I will find the best approach on next kernel update. There is a script to monitor Freq and Temp. If you can push the board to its limits and check if Freq and cpu core is reduced when Temp is very high.

`sudo ./h2-monitor.sh -w `

**Comment by Anoyomouse** [comment]
All applied, my BPi went from 27C to 31C, cpu frequencies also seem to fluctuate a little more, but i thin that's because it's trying to idle more

My application is not so heavy on processing, so this shouldn't be too much of a problem for me

**Comment by avafinger** [comment]
stable Kernel 4.17.9 has been released.

`sudo dpkg -i linux-image-4.17.9-m2z_1.0-2.deb`

and then:

`sync && sudo reboot`

Things are set back to normal Temp on this kernel update.
