### ISSUE TITLE
FEATURE REQUEST: arm64 version

### ISSUE THREAD

**Issue by minnixtx** [avafinger/bananapi-zero-ubuntu-base-minimal#37]
I noticed this is armv7l (32 bit), is there anyway you can generate a aarch64 image to match the 64 bit H2+ CPU on the bpm2z?

**Comment by avafinger** [comment]
I don't think so. Where did you get the information the H2+ is a 64-bit aarch?

> The ARM Cortex-A7 MPCore is a **32-bit microprocessor** core licensed by ARM Holdings implementing the ARMv7-A architecture announced in 2011

**Comment by minnixtx** [comment]
I'm sorry you are right. I have been working so much with the h5 in the orange pi zero that I got the 2 confused.
