### ISSUE TITLE
USB camera support

### ISSUE THREAD

**Issue by nordurljosahvida** [avafinger/bananapi-zero-ubuntu-base-minimal#53]
Hi, is USB camera supported by your image?

Thanks

**Comment by avafinger** [comment]
There is support for USB camera and DVP camera (OV5640)

https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/blob/master/README.md#working-with-cameras

**Comment by nordurljosahvida** [comment]
ok thanks, it somehow creates several media and video devices so i had to write a script to fetch the active one and inform octoprint which one it's using. will publish these soon. thanks
