### ISSUE TITLE
v3.10 broken,  wrong kernel, etc...

### ISSUE THREAD

**Issue by rlesac** [avafinger/bananapi-zero-ubuntu-base-minimal#61]
Bugs:

1. wrong / owner
2. wrong kernel
ubuntu@bpi-m2z:~$ uname -r
5.7.7-server

3. no modules for the kernel 
4. ubuntu@bpi-m2z:~$ ll /lib/modules
total 16
drwxr-xr-x  4 root root 4096 Mar 28 15:26 ./
drwxr-xr-x 41 root root 4096 Mar 28 20:41 ../
drwxr-xr-x  3 root root 4096 Mar 27 19:15 5.11.10-server/
drwxr-xr-x  3 root root 4096 Mar 28 15:45 5.7.10-server/

5. no kernels 5.7.10 nor 5.11.10

ubuntu@bpi-m2z:~$ ll /boot
total 24256
drwxrwxr-x  3 ubuntu ubuntu    4096 Apr  4 16:41 ./
drwxrwxr-x 18 ubuntu ubuntu    4096 Mar 27 13:23 ../
lrwxrwxrwx  1 root   root        20 Jan 15  2018 boot.scr -> bpi-m2-zero_boot.scr
-rw-r--r--  1 root   root     26300 Oct  8  2019 bpi-m2-zero-v4.dtb_5.3.5
-rw-rw-r--  1 ubuntu ubuntu   27017 Apr 26  2020 bpi-m2-zero-v4.dtb_5.6.5-server
-rw-r--r--  1 root   root     28817 Jun 28  2020 bpi-m2-zero-v4.dtb_5.7.6
-rw-r--r--  1 root   root     28813 Jul  4  2020 bpi-m2-zero-v4.dtb_5.7.7-server
lrwxrwxrwx  1 root   root        31 Apr  4 16:41 bpi-m2-zero.dtb -> bpi-m2-zero-v4.dtb_5.7.7-server
-rw-r--r--  1 root   root      1183 Nov 24  2018 bpi-m2-zero_boot.cmd
-rw-r--r--  1 root   root      1255 Nov 24  2018 bpi-m2-zero_boot.scr
-rw-rw-r--  1 ubuntu ubuntu  982455 Jan 18  2018 initrd.img
drwx------  2 root   root     16384 Nov  5  2017 lost+found/
lrwxrwxrwx  1 root   root        19 Apr  4 16:41 zImage -> zImage_5.7.7-server*
-rwxr-xr-x  1 root   root   5758032 Oct  8  2019 zImage_5.3.5*
-rwxrwxr-x  1 ubuntu ubuntu 5931848 Apr 26  2020 zImage_5.6.5-server*
-rwxr-xr-x  1 root   root   6000368 Jun 28  2020 zImage_5.7.6*
-rwxr-xr-x  1 root   root   6000720 Jul  4  2020 zImage_5.7.7-server*

So using the docs to change the kernel will make it unbootable.

**Comment by avafinger** [comment]
You are confusing things. Please, don't mix Ubuntu 19.10 Image with Ubuntu 20.04 LTS.
Kernel modules are in /usr/lib/modules, use the latest Image:
https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/v3.10


![2021-08-25-205238_1920x1056_scrot](https://user-images.githubusercontent.com/16623039/130879143-ee0e6f6f-b994-4572-bd06-a66487627aef.png)

**Comment by avafinger** [comment]
Flash v3.10 in a new sd card....

**Comment by rlesac** [comment]
> 
> 
> Flash v3.10 in a new sd card....
Formatted and flashed using your scripts two times, just to be sure.

**Comment by avafinger** [comment]
There is no such files in v3.10 like you printed here:

```
ubuntu@bpi-m2z:~$ ll /boot
total 24256
drwxrwxr-x 3 ubuntu ubuntu 4096 Apr 4 16:41 ./
drwxrwxr-x 18 ubuntu ubuntu 4096 Mar 27 13:23 ../
lrwxrwxrwx 1 root root 20 Jan 15 2018 boot.scr -> bpi-m2-zero_boot.scr
-rw-r--r-- 1 root root 26300 Oct 8 2019 bpi-m2-zero-v4.dtb_5.3.5
-rw-rw-r-- 1 ubuntu ubuntu 27017 Apr 26 2020 bpi-m2-zero-v4.dtb_5.6.5-server
-rw-r--r-- 1 root root 28817 Jun 28 2020 bpi-m2-zero-v4.dtb_5.7.6
-rw-r--r-- 1 root root 28813 Jul 4 2020 bpi-m2-zero-v4.dtb_5.7.7-server
lrwxrwxrwx 1 root root 31 Apr 4 16:41 bpi-m2-zero.dtb -> bpi-m2-zero-v4.dtb_5.7.7-server
-rw-r--r-- 1 root root 1183 Nov 24 2018 bpi-m2-zero_boot.cmd
-rw-r--r-- 1 root root 1255 Nov 24 2018 bpi-m2-zero_boot.scr
-rw-rw-r-- 1 ubuntu ubuntu 982455 Jan 18 2018 initrd.img
drwx------ 2 root root 16384 Nov 5 2017 lost+found/
lrwxrwxrwx 1 root root 19 Apr 4 16:41 zImage -> zImage_5.7.7-server*
-rwxr-xr-x 1 root root 5758032 Oct 8 2019 zImage_5.3.5*
-rwxrwxr-x 1 ubuntu ubuntu 5931848 Apr 26 2020 zImage_5.6.5-server*
-rwxr-xr-x 1 root root 6000368 Jun 28 2020 zImage_5.7.6*
-rwxr-xr-x 1 root root 6000720 Jul 4 2020 zImage_5.7.7-serve
```

**Comment by avafinger** [comment]
Here is the content of the /boot partition if you flash to a new card:
![2021-08-25-213411_1920x1056_scrot](https://user-images.githubusercontent.com/16623039/130881728-e1389c40-066b-4ba7-8b96-2b542b09c837.png)

**Comment by rlesac** [comment]
Turns out that the flash part was not writing to the boot partition, hence old kernel, modules mismatch, wifi issues.
I manually mounted the boot partition and copied the files. 
Working fine since, even wifi (except channels over 11, even though I changed the region).

**Comment by rlesac** [comment]
It's a weird error, so you might wanna add some basic checks in the flash script.
