### ISSUE TITLE
[SOLVED] cpu no longer @1200 MHz

### ISSUE THREAD

**Issue by gavan-x** [avafinger/bananapi-zero-ubuntu-base-minimal#62]
using  https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/v3.10

CPU mac Mhz: 1008

anyway to bring this back up as you had before?
The CPU  is rated for 1200 MHz.

**Comment by avafinger** [comment]
> anyway to bring this back up as you had before?

Can you remember which kernel was it?

**Comment by avafinger** [comment]
Can you try this one and report the results?
**Kernel 5.11.10-server**

[bpi-m2-zero-v4.dtb.tar.gz](https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/files/7071857/bpi-m2-zero-v4.dtb.tar.gz)

**Comment by avafinger** [comment]
In case you don't know how to install it, make sure you have a backup of the file **bpi-m2-zero-v4.dtb** in **/boot** prior to decompressing (untar) the file bpi-m2-zero-v4.dtb.tar.gz in **/boot** partition with **sudo** or **root**.

* create the link to the new dtb:
cd /boot
sudo ln -sf bpi-m2-zero-v4.dtb bpi-m2-zero.dtb

**Comment by gavan-x** [comment]
currently kernel 5.7.10

followed

```
  cd /boot
     sudo ln -sf bpi-m2-zero-v4.dtb_5.11.10-server bpi-m2-zero.dtb
     sudo ln -sf zImage_5.11.10-server zImage
     sudo reboot
```
as per docs, now 5.11.10 and CPU still @1008Mhz

```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               5
Model name:          Cortex-A7
Stepping:            r0p5
CPU max MHz:         1008.0000
CPU min MHz:         120.0000
BogoMIPS:            22.85
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```

followed up with  [bpi-m2-zero-v4.dtb.tar.gz](https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/files/7071857/bpi-m2-zero-v4.dtb.tar.gz) by placing in the /boot dir.

then 

```
cd /boot
sudo ln -sf bpi-m2-zero-v4.dtb bpi-m2-zero.dtb
```
Boom!

```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               5
Model name:          Cortex-A7
Stepping:            r0p5
CPU max MHz:         1200.0000
CPU min MHz:         120.0000
BogoMIPS:            48.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```
but I lost the red led power / heartbeat light, not sure what happened there.


Thanks!

**Comment by avafinger** [comment]
Hmmm,  It should not interfere with the heartbeat, watch the CPU Temp and stability issues. Use a really good heat sink!

**Comment by gavan-x** [comment]
Board works....Not sure what happened there.

Does Kernel 5.11.10-server have Mali support built in?
How to test?

**Comment by avafinger** [comment]
The "server" has no mali support.

If I remember correctly https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/v3.3 support mali gbm.

glmark2-2014.03 or kmscube
