### ISSUE TITLE
Mining with sgminer

### ISSUE THREAD

**Issue by gavan-x** [avafinger/bananapi-zero-ubuntu-base-minimal#64]
https://www.novaspirit.com/2017/12/21/gpu-mining-on-tinkerboard/

essentially the guide should work on all Mali SBC's.
Works fine on my tinkerboard.

I thought using the [image](https://github.com/avafinger/bananapi-zero-ubuntu-base-minimal/releases/tag/v3.3) with Mali gbm support would work.

Builds fine but get not OpenCL not found.

```
------------------------------------------------------------------------
sgminer 5.1.0
------------------------------------------------------------------------


Configuration Options Summary:

  Use git version......: yes
  libcurl(GBT+getwork).: Enabled: -lcurl
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: NOT FOUND. GPU mining support DISABLED
configure: error: OpenCL not found

```

**Comment by avafinger** [comment]
https://community.arm.com/developer/tools-software/graphics/f/discussions/9464/mali-400-mp2-opencl

**Comment by gavan-x** [comment]
confirmed Mali 400 no OPEN CL support!
