### ISSUE TITLE
USBSerial for initial console

### ISSUE THREAD

**Issue by adaptandadopt** [avafinger/bananapi-zero-ubuntu-base-minimal#69]
Would like to use usb serial console to boot and manage this device.  Is that possible with current pre-compiled kernels?

**Comment by avafinger** [comment]
Yes. You need a USB to TTL Serial Cable. Connect TX,RX and GND to the pins. (not on the headers).
Read here: https://wiki.banana-pi.org/Getting_Started_with_M2_Zero

**Comment by adaptandadopt** [comment]
What are the settings for debug serial? default for miniterm is 9600,8,n,1.  Link given above doesn't share those details.  Using FT232RL, if that matters.

**Comment by avafinger** [comment]
115200,8,n,1
